//HintName: PersonDto.g.cs
#nullable enable
/*  <auto-generated> ------------------------------------------------------------------------------ 
        This code was generated by Arisoul.SourceGenerators tool.
        Changes to this file may cause incorrect behavior and will be lost if
        the code is regenerated.
    </auto-generated> ------------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace GeneratorDebugConsumer
{
    public class PersonDto
    {
        public GeneratorDebugConsumer.DomainPerson Child { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}