//HintName: PersonCustom.g.cs
#nullable enable
/*  <auto-generated> ------------------------------------------------------------------------------ 
        This code was generated by Arisoul.SourceGenerators tool.
        Changes to this file may cause incorrect behavior and will be lost if
        the code is regenerated.
    </auto-generated> ------------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace DtoGenerator
{
    public partial class PersonCustom
    {
        public virtual string TestAgain { get; set; }
        public virtual string LastName { get; set; }
    }
}