//HintName: PersonExtensions.g.cs
#nullable enable
/*  <auto-generated> ------------------------------------------------------------------------------ 
        This code was generated by Arisoul.SourceGenerators tool.
        Changes to this file may cause incorrect behavior and will be lost if
        the code is regenerated.
    </auto-generated> ------------------------------------------------------------------------------*/

using System;

namespace DtoGenerator
{
    public static class PersonExtensions
    {
        public static PersonDto ToDto(this Person poco)
        {
            PersonDto dto = new PersonDto();

            dto.LastName = poco.LastName;

            return dto;
        }

        public static void FromDto(this Person poco, PersonDto dto)
        {
            poco.LastName = dto.LastName;
        }

        public static Person ToPoco(this PersonDto dto)
        {
            Person poco = new Person();

            poco.LastName = dto.LastName;

            return poco;
        }

        public static void FromPoco(this PersonDto dto, Person poco)
        {
            dto.LastName = poco.LastName;
        }
    }
}