//HintName: PersonExtensions.g.cs
#nullable enable
/*  <auto-generated> ------------------------------------------------------------------------------ 
        This code was generated by Arisoul.SourceGenerators tool.
        Changes to this file may cause incorrect behavior and will be lost if
        the code is regenerated.
    </auto-generated> ------------------------------------------------------------------------------*/

using System;

namespace GeneratorDebugConsumer
{
    public static class PersonExtensions
    {
        public static GeneratorDebugConsumer.PersonDto ToDto(this Person poco)
        {
            GeneratorDebugConsumer.PersonDto dto = new GeneratorDebugConsumer.PersonDto();

            dto.Name = poco.Name;
            dto.Description = poco.Description;

            return dto;
        }

        public static void FromDto(this Person poco, GeneratorDebugConsumer.PersonDto dto)
        {
            poco.Name = dto.Name;
            poco.Description = dto.Description;
        }

        public static Person ToPoco(this GeneratorDebugConsumer.PersonDto dto)
        {
            Person poco = new Person();

            poco.Name = dto.Name;
            poco.Description = dto.Description;

            return poco;
        }

        public static void FromPoco(this GeneratorDebugConsumer.PersonDto dto, Person poco)
        {
            dto.Name = poco.Name;
            dto.Description = poco.Description;
        }
    }
}