//HintName: PersonExtensions.g.cs

#nullable enable
// This code is autogenerated by Arisoul.SourceGenerators.

namespace GeneratorDebugConsumer
{
    public static class PersonExtensions
    {
        public static PersonDto ToDto(this Person poco)
        {
            PersonDto dto = new PersonDto();
    
    		dto.Name = poco.Name;
		dto.Description = poco.Description;
    
            return dto;
        }
    
        public static void FromDto(this Person poco, PersonDto dto)
        {
    		poco.Name = dto.Name;
		poco.Description = dto.Description;
        }
    
        public static Person ToPoco(this PersonDto dto)
        {
            Person poco = new Person();
    
    		poco.Name = dto.Name;
		poco.Description = dto.Description;
    
            return poco;
        }
    
        public static void FromPoco(this PersonDto dto, Person poco)
        {
    		dto.Name = poco.Name;
		dto.Description = poco.Description;
        }
    }
}