global using Arisoul.SourceGenerators.Extensions;
global using Arisoul.SourceGenerators.Writers;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Text;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;