//HintName: PersonDto.g.cs
#nullable enable

/*  <auto-generated> ------------------------------------------------------------------------------ 
        This code was generated by Arisoul.SourceGenerators tool.
        Changes to this file may cause incorrect behavior and will be lost if
        the code is regenerated.
    </auto-generated> ------------------------------------------------------------------------------*/

using System;

namespace GeneratorDebugConsumer
{
    public class PersonDto
    {
        public string TheName { get; set; }
        public string Description { get; set; }
    }
}