//HintName: PersonExtensions.g.cs

/*  <auto-generated> ------------------------------------------------------------------------------ 
        This code was generated by a tool.
        Changes to this file may cause incorrect behavior and will be lost if
        the code is regenerated.
    </auto-generated> ------------------------------------------------------------------------------*/

#nullable enable

namespace GeneratorDebugConsumer
{
    public static class PersonExtensions
    {
        public static PersonDto ToDto(this Person poco)
        {
            PersonDto dto = new PersonDto();
    
    		dto.Name = poco.Name;
		dto.Description = poco.Description;
    
            return dto;
        }
    
        public static void FromDto(this Person poco, PersonDto dto)
        {
    		poco.Name = dto.Name;
		poco.Description = dto.Description;
        }
    
        public static Person ToPoco(this PersonDto dto)
        {
            Person poco = new Person();
    
    		poco.Name = dto.Name;
		poco.Description = dto.Description;
    
            return poco;
        }
    
        public static void FromPoco(this PersonDto dto, Person poco)
        {
    		dto.Name = poco.Name;
		dto.Description = poco.Description;
        }
    }
}