//HintName: PersonDto.g.cs

#nullable enable
// This code is autogenerated by Arisoul.SourceGenerators.

namespace GeneratorDebugConsumer
{
    public class PersonDto
    {
    	public string Name { get; set; }
	public string Description { get; set; }
    }
}